name:                Engine
version:             0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - containers
  - aeson
  - bytestring
  - parsec
ghc-options:
      - -no-hs-main
      - -optl-Wl,--export=run_decomposition
      - -optl-Wl,--export=free_haskell_string
      - -optl-Wl,--export=hs_init
      - -optl-Wl,--export=malloc
      - -optl-Wl,--export=free


library:
  source-dirs: src

executables:
  Engine:
    main:                Main.hs
    source-dirs:         src
    dependencies:
      - Engine
      - base
      - aeson
      - bytestring
      - parsec

tests:
  Engine-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - Engine
      - QuickCheck
      - random
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N