name: Build Wasm (Subfolder)
on: [push]

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup GHC Wasm Toolchain
        run: |
          curl https://gitlab.haskell.org/ghc/ghc-wasm-meta/-/raw/master/bootstrap.sh | sh

      - name: Build to Wasm
        working-directory: ./Engine
        run: |
          source ~/.ghc-wasm/env
          
          wasm32-wasi-cabal update
          wasm32-wasi-cabal configure --ghc-options="-O2 -fno-code -fwrite-interface -fignore-interface-pragmas"
          wasm32-wasi-cabal build

          cp $(find dist-newstyle -name "*.wasm" -type f | head -n 1) ../engine.wasm

      - name: Upload Wasm
        uses: actions/upload-artifact@v4
        with:
          name: engine-wasm
          path: engine.wasm