name: Build Wasm Engine
on: [push]

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup GHC Wasm Toolchain
        run: |
          curl -L https://gitlab.haskell.org/ghc/ghc-wasm-meta/-/raw/master/bootstrap.sh | sh

      - name: Build to Wasm
        working-directory: ./Engine
        run: |
          source ~/.ghc-wasm/env
          wasm32-wasi-cabal update
          wasm32-wasi-cabal configure --allow-newer --ghc-options="-O2 -no-hs-main -optl-mexec-model=reactor -optl-Wl,--export=malloc -optl-Wl,--export=free -optl-Wl,--export=run_decomposition"
          wasm32-wasi-cabal build exe:Engine
          cp $(find dist-newstyle -name "*.wasm" -type f | head -n 1) ../engine.wasm

      - name: Upload Wasm Artifact
        uses: actions/upload-artifact@v4
        with:
          name: engine-wasm
          path: engine.wasm
